
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int POW = 47;
  public static final int GE = 39;
  public static final int UMINUS = 30;
  public static final int INTEGER_CONST = 48;
  public static final int INTEGER = 18;
  public static final int SEMI = 28;
  public static final int OUT = 23;
  public static final int MINUS = 43;
  public static final int WRITE = 11;
  public static final int NOT = 33;
  public static final int WRITET = 14;
  public static final int AND = 31;
  public static final int LT = 34;
  public static final int RPAR = 26;
  public static final int FUN = 3;
  public static final int OR = 32;
  public static final int BOOL = 19;
  public static final int COMMA = 27;
  public static final int DIV = 45;
  public static final int PLUS = 42;
  public static final int LOOP = 9;
  public static final int ASSIGN = 40;
  public static final int MAIN = 2;
  public static final int IF = 5;
  public static final int WRITELN = 12;
  public static final int ID = 16;
  public static final int LE = 35;
  public static final int EOF = 0;
  public static final int WRITEB = 13;
  public static final int RETURN = 15;
  public static final int TRUE = 51;
  public static final int error = 1;
  public static final int NULL = 17;
  public static final int DIVINT = 46;
  public static final int EQ = 36;
  public static final int REAL = 20;
  public static final int OUTPAR = 24;
  public static final int TIMES = 44;
  public static final int COLON = 29;
  public static final int ELSE = 7;
  public static final int READ = 10;
  public static final int WHILE = 8;
  public static final int STR_CONCAT = 41;
  public static final int REAL_CONST = 49;
  public static final int THEN = 6;
  public static final int NE = 37;
  public static final int END = 4;
  public static final int LPAR = 25;
  public static final int STRING = 21;
  public static final int FALSE = 52;
  public static final int STRING_CONST = 50;
  public static final int GT = 38;
  public static final int VAR = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "FUN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "LOOP",
  "READ",
  "WRITE",
  "WRITELN",
  "WRITEB",
  "WRITET",
  "RETURN",
  "ID",
  "NULL",
  "INTEGER",
  "BOOL",
  "REAL",
  "STRING",
  "VAR",
  "OUT",
  "OUTPAR",
  "LPAR",
  "RPAR",
  "COMMA",
  "SEMI",
  "COLON",
  "UMINUS",
  "AND",
  "OR",
  "NOT",
  "LT",
  "LE",
  "EQ",
  "NE",
  "GT",
  "GE",
  "ASSIGN",
  "STR_CONCAT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "DIVINT",
  "POW",
  "INTEGER_CONST",
  "REAL_CONST",
  "STRING_CONST",
  "TRUE",
  "FALSE"
  };
}

